trackType:
    - genome_spans
# override:
#     Track:
#         Height: 1
# uncomment this section to specify track-specific settings
# presets:
#     Preset_Name:
#         Family:
#             Option: value
